[theme]
primaryColor = "#0B3C68"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#1E293B"
font = "sans serif"

[client]
showErrorDetails = true

[server]
headless = true
enableCORS = true
